`FORMAT: 1A
HOST: http://localhost:4000/api

# Hephaestus

### SERVER PLANNER SERVICE
Write an API that calculates the server hardware for a data center (to host virtual machines).
Your API should return the number of servers that are required to host a non-empty collection of 
virtual machines.


This means you should implement the following operation (in UML definition):
`+calculate(serverType: Server, virtualMachines: VirtualMachine[1..*]): int`


All servers are from the same type. This type defines the hardware resources each server provides: 
CPU, RAM, HDD.

Each virtual machine is defined by the virtual hardware resources it needs (on a server): CPU, RAM, 
HDD.

The algorithm for the virtual machine distribution should implement a 'first fit' strategy.
This means there is no resource optimization or 'look back': Virtual machines are always allocated on 
the current or the next server (in case of limited resources).

# Calculate virtual machine distribution [/server/manage-vm]

## Calculate  virtual machine distribution  [POST ]

Sign Up to the Application takes a JSON object containing user credentials

+ Request (application/json)

            {
                "serverType":  {"CPU": 2, "RAM": 32, "HDD": 100},
                "virtualMachines": [
                    {"CPU": 1, "RAM": 16, "HDD": 10},
                    {"CPU": 1, "RAM": 16, "HDD": 10},
                    {"CPU": 2, "RAM": 32, "HDD": 100}
                ]
            }
            
+ Response 200 (application/json)
    
    + body

            {
                "message": "Successfully fetched the holding capacity for the server type",
                "result": {
                "value": 2
                }
            }